"""
Outbound "good morning" motivational call — inline-TwiML version (no public server).

Why inline TwiML: a fully two-way phone agent (one that *listens* to your answers and
replies) needs a publicly reachable webhook URL for Twilio to POST to — i.e. a tunnel.
This script needs none of that: we hand Twilio the entire spoken script up front via the
REST API's `twiml` parameter, so it works from any laptop with just the account creds.
That makes it the reliable path to *guarantee* a talking call lands.

Flow:  greet "Hi Ishaan, how are you?" → pause for your answer → explain it's been tasked
to give a motivational quote of the day → deliver the quote → a little more warmth → hang up.

The quote itself is generated by Nemotron (the project's "brain") at call time, with a
curated fallback if the free hosted endpoint stalls (a documented failure mode).

Run:  .venv/bin/python src/call_me.py
"""

import os
import sys
import time

from dotenv import load_dotenv
from twilio.rest import Client
from twilio.twiml.voice_response import VoiceResponse

load_dotenv()

ACCOUNT_SID = os.environ["TWILIO_ACCOUNT_SID"]
AUTH_TOKEN = os.environ["TWILIO_AUTH_TOKEN"]
FROM_NUMBER = os.environ["TWILIO_PHONE_NUMBER"]
TO_NUMBER = os.environ.get("TARGET_PHONE_NUMBER", "+18148268818")

# A warm, natural Amazon Polly neural voice (Twilio-hosted). Mirrors the project's
# "confident, friendly female" Cartesia default without needing Cartesia on the phone.
VOICE = os.getenv("TWILIO_SAY_VOICE", "Polly.Joanna-Neural")

# Curated fallback — used only if Nemotron is slow/unavailable. Strong, non-cheesy.
FALLBACK_QUOTE = (
    "Here it is. \"The secret of getting ahead is getting started. "
    "And the secret of getting started is breaking your complex, overwhelming tasks "
    "into small, manageable ones, and then starting on the first one.\" "
    "That's from Mark Twain."
)


def generate_quote() -> str:
    """Ask Nemotron for a fresh motivational quote of the day. Falls back fast on any
    trouble — the call must not hinge on the free endpoint's tail latency."""
    try:
        from openai import OpenAI

        client = OpenAI(
            api_key=os.environ["NVIDIA_API_KEY"],
            base_url="https://integrate.api.nvidia.com/v1",
        ).with_options(timeout=8.0, max_retries=1)
        resp = client.chat.completions.create(
            model=os.getenv("NVIDIA_LLM_MODEL", "nvidia/nemotron-3-nano-30b-a3b"),
            temperature=0.8,
            top_p=0.95,
            max_tokens=200,
            extra_body={"chat_template_kwargs": {"enable_thinking": False}},
            messages=[
                {
                    "role": "system",
                    "content": "You are a warm motivational coach speaking on a phone call.",
                },
                {
                    "role": "user",
                    "content": (
                        "Give me ONE motivational quote of the day to be read aloud. "
                        "Format: a single famous, genuine quote in double quotes, then "
                        "'— Author.' Then add one short, warm sentence (max 15 words) on "
                        "why it matters today. No preamble, no markdown, under 60 words total."
                    ),
                },
            ],
        )
        text = (resp.choices[0].message.content or "").strip()
        if text and len(text) > 20:
            print(f"[quote] Nemotron generated:\n{text}\n")
            return text
        print("[quote] Nemotron returned empty/short; using fallback.")
    except Exception as e:  # noqa: BLE001 — any failure → fallback, never block the call
        print(f"[quote] Nemotron unavailable ({e}); using fallback.")
    return FALLBACK_QUOTE


def build_twiml(quote: str) -> str:
    vr = VoiceResponse()
    vr.say("Hi Ishaan! How are you doing this morning?", voice=VOICE)
    vr.pause(length=3)  # space for you to answer
    vr.say(
        "I really hope you're doing well. So, I've been given one important job today, "
        "and that is to bring you your motivational quote of the day.",
        voice=VOICE,
    )
    vr.pause(length=1)
    vr.say(quote, voice=VOICE)
    vr.pause(length=1)
    vr.say(
        "Take a second and let that one sit with you. Whatever today throws at you, "
        "you've handled hard mornings before, and you'll handle this one too. "
        "Start with one small thing, and let the momentum carry you.",
        voice=VOICE,
    )
    vr.pause(length=1)
    vr.say(
        "That's all from me. Go have a great day, Ishaan. Talk soon.",
        voice=VOICE,
    )
    vr.hangup()
    return str(vr)


def main() -> None:
    quote = generate_quote()
    twiml = build_twiml(quote)
    print("[twiml] built:\n" + twiml + "\n")

    client = Client(ACCOUNT_SID, AUTH_TOKEN)
    call = client.calls.create(to=TO_NUMBER, from_=FROM_NUMBER, twiml=twiml)
    print(f"[call] placed: sid={call.sid}  {FROM_NUMBER} -> {TO_NUMBER}")

    # Poll until the call leaves the queue and reaches a terminal-ish state.
    terminal = {"completed", "busy", "failed", "no-answer", "canceled"}
    for _ in range(40):  # ~2 min max
        time.sleep(3)
        call = client.calls(call.sid).fetch()
        print(f"[call] status={call.status}")
        if call.status in terminal:
            break
    if call.status in {"failed", "no-answer", "busy", "canceled"}:
        print(f"[call] did not connect: {call.status}")
        sys.exit(1)
    print(f"[call] final status: {call.status}")


if __name__ == "__main__":
    main()
