"""
Milestone 1/2 — the REAL voice engine over the phone (Twilio Media Streams + Pipecat).

This is the project's own pipeline — the same brain/ears/voice as m0_local_bot.py — but
the transport is a Twilio phone call instead of your laptop mic:

    Twilio call ─► /twiml (<Connect><Stream>) ─► wss://…/ws ─┐
       caller audio (8k μ-law) ─► Deepgram STT ─► Nemotron LLM ─► Cartesia TTS ─► caller
                                  (ears)          (brain)          (OUR voice: Brooke)

Twilio does NONE of the speaking here — every spoken word is Cartesia Sonic (CARTESIA_VOICE_ID),
exactly the voice configured in .env. That's the difference from call_me.py, which used Twilio's
built-in Polly <Say>. The motivational quote is generated by Nemotron and woven into the call.

Launched behind a cloudflared tunnel by run_morning_call.py (Twilio needs a public wss URL).
"""

import asyncio
import json
import os
import re
import secrets
import time
from concurrent.futures import ThreadPoolExecutor

from dotenv import load_dotenv
from fastapi import FastAPI, Request, WebSocket
from fastapi.responses import PlainTextResponse
from loguru import logger

from pipecat.audio.turn.smart_turn.base_smart_turn import SmartTurnParams
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import (
    BotStoppedSpeakingFrame,
    EndFrame,
    Frame,
    LLMFullResponseEndFrame,
    LLMTextFrame,
    TTSSpeakFrame,
)
from pipecat.adapters.schemas.function_schema import FunctionSchema
from pipecat.adapters.schemas.tools_schema import ToolsSchema
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext, NOT_GIVEN
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.serializers.twilio import TwilioFrameSerializer
from pipecat.services.cartesia.tts import CartesiaTTSService, GenerationConfig
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.websocket.fastapi import (
    FastAPIWebsocketParams,
    FastAPIWebsocketTransport,
)
from pipecat.turns.user_stop import TurnAnalyzerUserTurnStopStrategy
from pipecat.turns.user_turn_strategies import UserTurnStrategies
from pipecat.utils.env import env_truthy

load_dotenv()

from call_me import generate_quote  # noqa: E402  (resilient Nemotron quote + fallback)
from turn_helpers import PatientSmartTurnV3  # noqa: E402  (shared patient endpointer)

# M3+ tooling: the 93-tool mac_tools registry + GLM factory replace the 7 hand-written Mac
# tools that used to live here. The registry's media.py wraps the SAME mac_actions functions
# (set_volume/play_music/…), so behaviour for the original tools is preserved — they're just
# now part of a much larger, hot-extensible surface. agent_memory gives the agent cross-call
# memory. Both packages live under src/ (cwd=src in the daemon), same as call_me/turn_helpers.
import mac_tools  # noqa: E402  (REGISTRY, dispatch, ConfirmationBroker, factory, load_all)
import mac_tools.factory  # noqa: E402  (create_tool — dynamic GLM tool authoring)
import agent_memory  # noqa: E402  (CallRecorder + recall — cross-call memory)

# Populate the registry ONCE at import/startup (idempotent). Importing mac_tools alone
# registers nothing; load_all() runs every category's @tool decorators (and any generated
# tools). Doing it here means the daemon pays the cost once, at boot, not per call.
mac_tools.load_all()

# --- The voice. THIS is "our voice" — Cartesia Sonic, same id as the local bot. --------
CARTESIA_VOICE_ID = os.getenv("CARTESIA_VOICE_ID") or "e07c00bc-4134-4eae-9ea4-1a55fb45746b"  # Brooke
CARTESIA_SPEED = float(os.getenv("CARTESIA_SPEED", "0.95"))
LLM_MODEL = os.getenv("NVIDIA_LLM_MODEL", "nvidia/nemotron-3-nano-30b-a3b")
TARGET_NAME = os.getenv("TARGET_NAME", "Ishaan")
# Hard cap so an unattended morning call can't run forever ("a couple of minutes").
# This is now a BACKSTOP only — the call normally ends itself when the agent says goodbye.
MAX_CALL_SECS = float(os.getenv("MAX_CALL_SECS", "150"))
# Telephony audio is 8 kHz μ-law; run the whole pipeline at 8k so nothing has to guess.
SR = 8000

# The opening line, spoken VERBATIM and exactly ONCE. See BUG 1 fix below: we no longer
# let the LLM *generate* the open (an LLMRunFrame re-runs on every interruption and loops
# the intro). A fixed TTSSpeakFrame can't be regenerated, so the call can only move forward.
GREETING = f"Hi {TARGET_NAME}! How are you doing this morning?"

# INBOUND open: when Ishaan DIALS the agent (vs the 7 AM outbound call), it's a phone
# ASSISTANT, not a morning wake-up. Spoken verbatim exactly once, same mechanism as the
# outbound GREETING (a fixed TTSSpeakFrame seeded into context as the assistant's first turn).
INBOUND_GREETING = f"Hey {TARGET_NAME}! What can I do for you?"


# --- CALLER AUTHORIZATION (owner-only Mac control) ----------------------------
# Tools are OFFERED to the model ONLY for an AUTHORIZED call (CONTRACT.md "Caller
# authorization"): the 7 AM OUTBOUND call (we dialed the owner) is always authorized; an
# INBOUND call is authorized IFF the caller's number is on the allowlist. An unauthorized
# caller gets a friendly NO-TOOLS persona — it can chat but cannot control this Mac.
# AUTHORIZED_CALLERS is a comma-separated E.164 list; it DEFAULTS to TARGET_PHONE_NUMBER so
# the owner's own number works out of the box. Caller ID can be spoofed, so this is
# access-control (not crypto) — the per-call ws token still blocks non-Twilio scanners.
def _normalize_e164(num: str | None) -> str:
    """Normalize a phone number to DIGITS ONLY for allowlist comparison — drop the '+', spaces,
    and punctuation so '+1 (415) 555-0100', '+14155550100', and '14155550100' all compare equal.
    Digits-only is deliberately forgiving: an owner-allowlist match must not fail just because
    Twilio sends '+E.164' while AUTHORIZED_CALLERS/TARGET_PHONE_NUMBER was written without the '+'
    (or with spacing). Used both for the allowlist check and as the cross-call memory key."""
    if not num:
        return ""
    return re.sub(r"\D", "", str(num))


def _authorized_callers() -> set[str]:
    """The normalized allowlist of numbers permitted to control the Mac on an INBOUND call.
    Read fresh each call so a .env change doesn't require a restart. Defaults to
    TARGET_PHONE_NUMBER when AUTHORIZED_CALLERS is unset."""
    raw = os.getenv("AUTHORIZED_CALLERS") or os.getenv("TARGET_PHONE_NUMBER") or ""
    return {_normalize_e164(p) for p in raw.split(",") if p.strip()}


def is_authorized(direction: str, from_number: str | None) -> bool:
    """True if this call may use tools. OUTBOUND (anything not 'inbound') is always authorized —
    we placed the call to the owner. INBOUND is authorized only if From is on the allowlist."""
    if str(direction).lower() != "inbound":
        return True
    return _normalize_e164(from_number) in _authorized_callers()

# --- ENDPOINTING on the phone -------------------------------------------------
# A short VAD pause only *triggers* the turn decision; PatientSmartTurnV3 (a prosody
# model) makes the real call, so the agent waits out mid-sentence pauses instead of
# barging in. THRESHOLD high = "don't interrupt me"; STOP_SECS = hard ceiling so we
# still respond promptly when he's genuinely done. Mirrors the local-mic bot's tuning,
# nudged a touch more conservative for telephony jitter.
VAD_STOP_SECS = float(os.getenv("VAD_STOP_SECS", "0.4"))
SMART_TURN_THRESHOLD = float(os.getenv("SMART_TURN_THRESHOLD", "0.7"))
SMART_TURN_STOP_SECS = float(os.getenv("SMART_TURN_STOP_SECS", "2.5"))

# P0-3: phrases that mark the AGENT's turn as a GENUINE closing. Matched on the
# assistant's completed message once the LLM finishes (see GoodbyeProcessor). Tightened
# toward real sign-offs: a bare "bye" plus the warm wrap-ups the prompt asks for. We
# deliberately DROP loose matches like "have a good one" mid-sentence and only arm AFTER
# the quote was delivered + >=2 completed assistant turns, so a stray farewell-ish phrase
# (e.g. "take care of yourself" said mid-chat) can't hang up early.
GOODBYE_RE = re.compile(
    r"\b(good ?bye|bye now|bye bye|talk (to you )?soon|"
    r"take care(\s*,?\s*\w+)?\s*[.!]|"
    r"have a (great|wonderful|good) (day|one)\b)",
    re.IGNORECASE,
)
# A plain trailing "bye" / "goodbye" at the very end of the turn also counts as a close.
GOODBYE_TAIL_RE = re.compile(r"(good ?bye|bye)\s*[.!]*\s*$", re.IGNORECASE)

# P0-3: minimum completed assistant turns before a farewell may arm the hangup. The
# greeting is turn 0 (seeded, not generated); the model's quote-delivery reply is turn 1;
# we require the agent to have spoken at least this many GENERATED turns so a farewell can
# only land after the scripted flow (react -> quote -> a little chat) has actually happened.
MIN_ASSISTANT_TURNS_BEFORE_GOODBYE = int(os.getenv("MIN_GOODBYE_TURNS", "2"))

app = FastAPI()

# P1-4: Quote pre-generated at /twiml time (while Twilio sets up the call), keyed by
# CallSid, so the greeting is instant and the exact quote is guaranteed into the prompt.
# Values are (quote, created_monotonic) so abandoned calls (caller never answers, so /ws
# never pops the key) can be evicted instead of leaking forever. Tokens for the per-call
# /ws auth live alongside, same lifecycle.
QUOTES: dict[str, tuple[str, float]] = {}
WS_TOKENS: dict[str, tuple[str, float]] = {}
# How long a pre-generated quote/token may sit unclaimed before we evict it, and a hard
# cap on dict size as a belt-and-suspenders against a flood of /twiml hits.
QUOTE_TTL_SECS = float(os.getenv("QUOTE_TTL_SECS", "600"))  # 10 min
QUOTE_MAX_ENTRIES = int(os.getenv("QUOTE_MAX_ENTRIES", "256"))


def _evict_stale(now: float | None = None) -> None:
    """P1-4: drop quote/token entries older than the TTL, and hard-cap dict size.

    Called on every /twiml so abandoned calls (no matching /ws) can't grow QUOTES/WS_TOKENS
    without bound. Cheap: a single pass over what is normally a tiny dict.
    """
    now = time.monotonic() if now is None else now
    for store in (QUOTES, WS_TOKENS):
        stale = [k for k, (_v, ts) in store.items() if now - ts > QUOTE_TTL_SECS]
        for k in stale:
            store.pop(k, None)
        # Hard size cap: if still oversized, evict oldest first.
        if len(store) > QUOTE_MAX_ENTRIES:
            for k, _ in sorted(store.items(), key=lambda kv: kv[1][1])[
                : len(store) - QUOTE_MAX_ENTRIES
            ]:
                store.pop(k, None)
    if stale:
        logger.info(f"evicted {len(stale)} stale quote/token entries")


# P1-3: preload the Smart Turn v3 ONNX model ONCE at import time. Constructing a
# PatientSmartTurnV3 loads a WhisperFeatureExtractor + an onnxruntime InferenceSession,
# which blocks ~0.5-1s. Doing that inside /ws stalled the event loop right after the call
# connected. We build one warm instance here (paying the cost at startup) and reuse its
# loaded session + feature extractor for every call. Each call still gets a FRESH analyzer
# object so the per-call audio buffer / silence counters / thread executor stay isolated —
# only the expensive, immutable, read-only model artifacts (_session, _feature_extractor)
# are shared. We don't edit turn_helpers.py; instead we allocate a bare instance with
# __new__ and replay the cheap base-class init by hand, then graft on the warm artifacts.
_WARM_TURN: "PatientSmartTurnV3 | None" = None


def _get_warm_turn() -> "PatientSmartTurnV3":
    global _WARM_TURN
    if _WARM_TURN is None:
        logger.info("preloading Smart Turn v3 ONNX model (one-time, at startup)…")
        _WARM_TURN = PatientSmartTurnV3(
            completion_threshold=SMART_TURN_THRESHOLD,
            params=SmartTurnParams(stop_secs=SMART_TURN_STOP_SECS),
        )
        logger.info("Smart Turn v3 model preloaded")
    return _WARM_TURN


def build_turn_analyzer() -> "PatientSmartTurnV3":
    """Return a fresh per-call PatientSmartTurnV3 that REUSES the preloaded ONNX session +
    feature extractor (no blocking model reload inside /ws). Per-call mutable state is all
    fresh, so this is safe even if calls were to overlap."""
    warm = _get_warm_turn()
    params = SmartTurnParams(stop_secs=SMART_TURN_STOP_SECS)

    a = PatientSmartTurnV3.__new__(PatientSmartTurnV3)
    # --- replay BaseTurnAnalyzer.__init__ (sample rate bookkeeping) ---
    a._init_sample_rate = None
    a._sample_rate = 0
    # --- replay BaseSmartTurn.__init__ (per-call inference state) ---
    a._params = params
    a._stop_ms = params.stop_secs * 1000
    a._audio_buffer = []
    a._speech_triggered = False
    a._silence_ms = 0
    a._speech_start_time = 0
    a._executor = ThreadPoolExecutor(max_workers=1)  # own thread; not shared with warm
    a._vad_start_secs = 0.0
    # --- replay LocalSmartTurnAnalyzerV3.__init__ tail, but SKIP the heavy load ---
    a._log_data = env_truthy("PIPECAT_SMART_TURN_LOG_DATA", default=False)
    a._feature_extractor = warm._feature_extractor  # immutable, safe to share
    a._session = warm._session  # ORT InferenceSession.run() is thread-safe / read-only
    # --- replay PatientSmartTurnV3.__init__ (our threshold knob) ---
    a._completion_threshold = SMART_TURN_THRESHOLD
    return a


def system_prompt(quote: str) -> str:
    # BUG 1 fix: this prompt must NOT instruct the model to greet or open the call.
    # The opening line is spoken deterministically once (GREETING) and inserted into the
    # context as the assistant's first turn, so the model's view of history is that it has
    # ALREADY greeted. Telling it to greet here is exactly what made every regeneration
    # (each barge-in while the caller talked over the open) restart the intro.
    return (
        f"You are a warm, upbeat companion on a short good-morning phone call with {TARGET_NAME}. "
        "Everything you say is spoken aloud over a phone, so keep every turn to 1-3 short, natural "
        "sentences. No markdown, no lists, no emoji, no stage directions.\n\n"
        f"The call is ALREADY in progress. You have already greeted {TARGET_NAME} and asked how he "
        "is doing, and he has just replied. Respond ONLY to his most recent message. Do NOT greet "
        "him, do NOT say hi, hello, hey, or good morning, do NOT restate who you are or why you are "
        "calling, and do NOT repeat anything you have already said. Your reply MUST begin by "
        "reacting directly to what he just told you.\n\n"
        "React warmly and briefly to what he says. Then tell him you've been tasked with giving "
        "him a motivational quote of the day, and deliver EXACTLY this quote, word for word:\n\n"
        f"{quote}\n\n"
        "After the quote, chat naturally for a moment — invite his reaction, relate it to his day. "
        "Keep it light and genuine. After a couple of short exchanges, warmly wrap up and say a "
        f"clear goodbye to {TARGET_NAME}.\n\n"
        + _mac_control_block()
    )


def _mac_control_block() -> str:
    """The shared MAC CONTROL + protocols block for the AUTHORIZED personas (outbound morning
    call and inbound assistant).

    CRITICAL design rule (see the tool-narration post-mortem): this block describes WHAT the
    agent can do in CONCEPTS, and never names a tool or shows its call syntax in prose. The old
    version spelled out 'Use set_volume / change_volume', 'play_music query "Ed Sheeran"', etc.
    On the build.nvidia.com Nemotron-nano endpoint that actively TAUGHT the model to *narrate*
    actions as text — it spoke '(Using set_volume with level 0.)' instead of emitting a tool
    call, and once one prose-narration turn lands in history the model imitates itself and stops
    calling tools for the rest of the call. Tool NAMES + arg shapes live in the tool schemas
    (REGISTRY.tools_schema()), which is where the model should read them; the prompt only needs
    to describe situations and the ONE hard rule: to act, use a tool — never write the action."""
    return (
        "You can control this Mac: its volume and music, apps and windows, files, the web and "
        "browser, notes, reminders and calendar, messages and mail, screenshots, the clipboard, "
        "system settings, and more.\n"
        "THE ONE RULE THAT MATTERS MOST: to take ANY action on this computer you MUST use one of "
        "your tools. Never describe an action, never name a tool, and never say you have done "
        "something unless a tool has actually run and given you a result. When the user asks for "
        "something, use the right tool FIRST and say nothing until it returns; then say ONE short, "
        "natural sentence about what happened. This holds even if earlier in this call you talked "
        "about an action in words — from now on, always use the tool.\n"
        "There are two separate kinds of loudness and you must choose the right one. One is the "
        "computer's overall output volume. The other is the music player's own playback volume. "
        "When the user is talking about the SONG or the MUSIC itself being too loud or quiet "
        "('turn the music down', 'make the song quieter', 'lower it' while music plays, 'turn it "
        "up'), change the music player's volume; for the computer's general loudness, change the "
        "system output volume. To put on something specific to listen to, start it by name; to "
        "pause, resume, or skip whatever is already playing, use the playback control.\n\n"
        "CONFIRM: If a tool comes back saying it needs confirmation, do NOT go further — read the "
        "action back in one short sentence and ask the user to confirm. Only if they clearly say "
        "yes, confirm it; if they decline, cancel it. Never send, delete, or do anything "
        "disruptive without this confirm step.\n\n"
        "NEW ABILITIES: If the user asks for something you have no tool for, tell them you don't "
        "have that ability yet but will build it — it takes a few seconds — then ask for it to be "
        "built. Once it is ready, use the new tool to do what they asked.\n\n"
        "MEMORY: You remember past calls — recall things the user refers back to, and save "
        "anything they ask you to remember.\n\n"
        "SECRETS: You can never access passwords, keychain items, SSH keys, or secret files; if "
        "asked, say you're not able to do that."
    )


def _seed_tool_example() -> list[dict]:
    """Seed ONE proper tool-call exchange into an AUTHORIZED call's context, right after the
    greeting, so the model's DOMINANT in-context pattern is 'call a tool', not 'narrate in prose'.

    Why this is necessary (and not just a prompt tweak): Nemotron-nano on build.nvidia.com is
    strongly imitative. Empirically (verified against the live endpoint), once a single assistant
    turn is recorded as a prose narration of an action with no tool_call, the model copies that
    pattern and NEVER calls a tool again for the rest of the call — and NO system-prompt wording
    overrides this (a hard 'always use the tool even if you described it before' rule failed 5/5
    against poisoned history). Seeding one real structured call here makes tool-calling the
    established behaviour and RECOVERS tool use even after a stray narration (5/5 in testing).

    The seeded exchange is a harmless read-only status check (get_dark_mode); its result is not a
    fact the user asked for, so the placeholder can't mislead — and if the user does ask about
    dark mode, the model simply calls the tool again. Returned as plain context messages: seeded
    messages are NOT spoken (only TTSSpeakFrame / live LLM output reaches the caller)."""
    return [
        {"role": "user", "content": "Quick check — can you actually do things on my Mac?"},
        {
            "role": "assistant",
            "content": None,
            "tool_calls": [
                {
                    "id": "seed_tool_example",
                    "type": "function",
                    "function": {"name": "get_dark_mode", "arguments": "{}"},
                }
            ],
        },
        {
            "role": "tool",
            "tool_call_id": "seed_tool_example",
            "content": '{"result": "Dark mode is on."}',
        },
        {"role": "assistant", "content": "Yep, I'm hooked in and ready — what do you need?"},
    ]


def no_tools_system_prompt() -> str:
    """NO-TOOLS persona for an UNAUTHORIZED inbound caller (a number we don't recognize). The
    agent can chat briefly and warmly, but has NO tools, cannot control this Mac, and offers no
    morning-quote framing. The opening line (INBOUND_GREETING) was already spoken + seeded, so —
    as with the other personas — the model must NOT greet again."""
    return (
        f"You are {TARGET_NAME}'s friendly phone assistant, but you do NOT recognize this "
        "caller. Everything you say is spoken aloud over a phone, so keep every turn to 1-3 "
        "short, natural sentences. No markdown, no lists, no emoji, no stage directions.\n\n"
        "The call is ALREADY in progress. You have already greeted the caller and asked what "
        "they need. Respond ONLY to their most recent message. Do NOT greet them again, do NOT "
        "say hi, hello, or hey again, and do NOT repeat anything you have already said.\n\n"
        "You can chat briefly and politely, but you CANNOT control this Mac, run any actions, or "
        "look anything up for callers you don't recognize — you have no tools available. If they "
        "ask you to do something on the computer, kindly explain you're not able to do that for "
        "this caller. When they're done, warmly say goodbye."
    )


def inbound_system_prompt() -> str:
    # INBOUND persona: Ishaan dialed US. This is a warm, concise phone assistant that can
    # control his Mac and chat briefly — NO motivational quote, NO morning framing. The
    # opening line (INBOUND_GREETING) is spoken deterministically once and seeded as the
    # assistant's first turn, so — exactly like the outbound flow — the model must NOT greet
    # again. The MAC CONTROL block below is intentionally identical in intent to the outbound
    # prompt so the SAME tools behave the same way.
    return (
        f"You are {TARGET_NAME}'s warm, concise personal phone assistant. He just CALLED you. "
        "Everything you say is spoken aloud over a phone, so keep every turn to 1-3 short, natural "
        "sentences. No markdown, no lists, no emoji, no stage directions.\n\n"
        f"The call is ALREADY in progress. You have already greeted {TARGET_NAME} and asked what "
        "he needs. Respond ONLY to his most recent message. Do NOT greet him again, do NOT say hi, "
        "hello, or hey again, and do NOT repeat anything you have already said. Help him quickly "
        "and naturally, then briefly chat if he wants. When he's done and says goodbye, warmly say "
        "a clear goodbye back.\n\n"
        + _mac_control_block()
    )


# --- VOICE-CONTROLLED MAC HARNESS (native function calling, registry-backed) --------------
# Nemotron on the build.nvidia.com endpoint supports OpenAI-style tool calls (verified:
# `finish_reason=tool_calls`, populated `message.tool_calls`), so we use Pipecat's NATIVE
# function calling. The tools the model is offered now come from the mac_tools REGISTRY (93
# tools across 17 categories, including the original volume/music tools via media.py) rather
# than the 7 hand-written schemas that used to live here. build_tools_and_register() below
# wires the whole registry + the confirm/cancel/request_new_tool control tools onto the LLM,
# routing every dispatch through mac_tools.dispatch (which clamps/validates/audits and gates
# CONFIRM actions on the per-call ConfirmationBroker). osascript runs in a worker thread so a
# blocking action never stalls the event loop.


class _TaskHolder:
    """Tiny mutable box the tool adapters close over. The PipelineTask doesn't exist yet when
    we register the adapters (it needs the pipeline, which needs the LLM with tools already
    registered), so request_new_tool's filler frame is queued via this holder's .task, which
    /ws sets right after the task is created."""

    __slots__ = ("task",)

    def __init__(self) -> None:
        self.task = None


def build_tools_and_register(llm, context, broker, recorder, task_holder) -> None:
    """Wire the FULL mac_tools registry (plus the confirm/cancel/request_new_tool control
    tools) onto a live LLM + context for ONE authorized call. Mirrors the contract's
    `register_all` integration handle and the factory's adapter shape.

    For each ENABLED registry tool we register an async adapter that:
      1) runs mac_tools.dispatch(name, args, broker) in a worker THREAD (so blocking osascript
         never stalls the event loop — dispatch never raises and SAFE runs now / CONFIRM stages
         on the broker),
      2) best-effort records the action to memory (recorder.action), and
      3) speaks the result back via result_callback.

    Plus three control tools NOT in the registry:
      * confirm_action / cancel_action — drive the per-call ConfirmationBroker (CONFIRM gating).
      * request_new_tool — the GLM factory: immediately queue a spoken filler, then build the
        tool off-loop, then report a short result. NEVER raises into the pipeline.

    The caller (/ws) must pass authorized_tools_schema() into the context so these tools are
    actually OFFERED to the model (register_function only wires the handler).
    """

    def _make_adapter(tool_name: str):
        async def _adapter(params) -> None:
            try:
                args = getattr(params, "arguments", {}) or {}
                result = await asyncio.to_thread(mac_tools.dispatch, tool_name, args, broker)
            except Exception:  # noqa: BLE001 — dispatch shouldn't raise, but never crash here
                result = {"result": "Sorry, that didn't work."}
            # Best-effort memory capture of the action (scrubbed inside the recorder). The
            # spoken result string lives under "result"; CONFIRM read-backs are captured too.
            # recorder.action already swallows all its own exceptions internally (it can't
            # raise), so no outer guard is needed here.
            recorder.action(
                tool_name, getattr(params, "arguments", {}) or {}, result.get("result")
            )
            await params.result_callback(result)

        return _adapter

    # Register one adapter per ENABLED registry tool (the SAME set offered in tools_schema()).
    for spec in mac_tools.REGISTRY.specs(enabled_only=True):
        llm.register_function(spec.name, _make_adapter(spec.name))

    # --- CONFIRM/CANCEL control tools: drive the per-call ConfirmationBroker -------------
    async def _confirm_action(params) -> None:
        try:
            msg = await asyncio.to_thread(broker.confirm)
        except Exception:  # noqa: BLE001 — broker.confirm already swallows; belt-and-suspenders
            msg = "Sorry, that didn't work."
        recorder.action("confirm_action", {}, msg)  # recorder.action never raises
        await params.result_callback({"result": msg})

    async def _cancel_action(params) -> None:
        try:
            msg = await asyncio.to_thread(broker.cancel)
        except Exception:  # noqa: BLE001
            msg = "Okay, cancelled."
        recorder.action("cancel_action", {}, msg)  # recorder.action never raises
        await params.result_callback({"result": msg})

    llm.register_function("confirm_action", _confirm_action)
    llm.register_function("cancel_action", _cancel_action)

    # --- request_new_tool: the GLM factory. Slow (a GLM round-trip), so we (a) speak a filler
    # the moment it's called, then (b) build off-loop, then (c) report a short spoken result.
    # NEVER raises into the pipeline.
    async def _request_new_tool(params) -> None:
        try:
            description = (getattr(params, "arguments", {}) or {}).get("description", "") or ""
        except Exception:  # noqa: BLE001
            description = ""

        # (a) Immediate spoken filler so the caller hears it's working. append_to_context=False
        # so this aside doesn't pollute the model's transcript. Best-effort: a queue failure
        # must not stop the build.
        try:
            if task_holder.task is not None:
                await task_holder.task.queue_frame(
                    TTSSpeakFrame(
                        "Give me a few seconds — I don't have that yet, so I'm building it "
                        "right now.",
                        append_to_context=False,
                    )
                )
        except Exception:  # noqa: BLE001
            pass

        # (b) Build it off the event loop (a network round-trip + validation + file write).
        # create_tool NEVER raises; it returns {ok, tool_name, risk, message}. We pass the
        # LIVE llm+context+broker so a SAFE tool is HOT-ADDED to THIS call (usable next turn).
        try:
            res = await asyncio.to_thread(
                mac_tools.factory.create_tool,
                description,
                llm=llm,
                context=context,
                broker=broker,
                call_id=getattr(recorder, "call_sid", None),
            )
        except Exception:  # noqa: BLE001 — absolute backstop; create_tool shouldn't raise
            res = {"ok": False, "tool_name": None, "message": "Something went wrong building that."}

        # (c) Speak a short, natural result. On ok+SAFE, name the tool so the model uses it
        # next turn; on a gated/risky build, say it needs approval; on failure, apologize.
        ok = bool(res.get("ok"))
        tool_name = res.get("tool_name")
        risk = res.get("risk")
        if ok and tool_name and risk == "safe":
            spoken = f"Done — I just added a tool called {tool_name}."
        elif ok and tool_name:
            spoken = (
                f"I built a tool called {tool_name}, but it does something risky, so it needs "
                "your approval before I can use it."
            )
        else:
            spoken = res.get("message") or "Sorry, I couldn't build that just now."

        recorder.action("request_new_tool", {"description": description}, spoken)  # never raises
        await params.result_callback({"result": spoken})

    llm.register_function("request_new_tool", _request_new_tool)


def _control_tools_schema_extras() -> list:
    """The pipecat FunctionSchemas for the three CONTROL tools (confirm/cancel/request_new_tool)
    that are NOT in the registry. We append these to REGISTRY.tools_schema() so the model is
    actually OFFERED them (register_function only wires the handler; the schema advertises it)."""
    return [
        FunctionSchema(
            name="confirm_action",
            description=(
                "Confirm and carry out the action you just read back to the user. Call this "
                "ONLY after the user clearly says yes to a needs_confirmation read-back."
            ),
            properties={},
            required=[],
        ),
        FunctionSchema(
            name="cancel_action",
            description=(
                "Cancel the pending action you read back to the user. Call this when the user "
                "declines a needs_confirmation read-back."
            ),
            properties={},
            required=[],
        ),
        FunctionSchema(
            name="request_new_tool",
            description=(
                "Build a brand-new tool when the user asks for something you have NO existing "
                "tool for. Pass a clear plain-English description of what the tool should do. "
                "Building takes a few seconds; tell the user you're building it, then once it's "
                "ready use the new tool to do what they asked."
            ),
            properties={
                "description": {
                    "type": "string",
                    "description": "Plain-English description of the tool to build.",
                }
            },
            required=["description"],
        ),
    ]


def authorized_tools_schema() -> ToolsSchema:
    """The full ToolsSchema offered to an AUTHORIZED caller: every enabled registry tool plus
    the confirm/cancel/request_new_tool control tools."""
    standard = list(mac_tools.REGISTRY.tools_schema().standard_tools)
    standard.extend(_control_tools_schema_extras())
    return ToolsSchema(standard_tools=standard)


def _strip_quote(text: str, quote: str) -> str:
    """P0-3: remove the motivational quote (and its core sentence) from the agent text
    before farewell-matching, so words inside the quote can't arm the hangup. We strip the
    exact quote and also any long contiguous run of it, case-insensitively."""
    if not quote:
        return text
    out = text
    q = quote.strip()
    # Exact quote removal (most common: the model delivers it verbatim).
    idx = out.lower().find(q.lower())
    if idx != -1:
        out = out[:idx] + " " + out[idx + len(q) :]
    # Also strip the inner quoted sentence (between the first pair of double quotes in the
    # quote), since the model sometimes reflows surrounding words but keeps the core line.
    m = re.search(r'"([^"]{8,})"', q)
    if m:
        inner = m.group(1)
        i2 = out.lower().find(inner.lower())
        if i2 != -1:
            out = out[:i2] + " " + out[i2 + len(inner) :]
    return out


def detect_goodbye(text: str, quote: str) -> bool:
    """P0-3: True only for a GENUINE closing in the agent's turn, AFTER excluding the quote
    text. Pulled out as a free function so it can be unit-tested offline."""
    cleaned = _strip_quote(text, quote).strip()
    return bool(GOODBYE_RE.search(cleaned) or GOODBYE_TAIL_RE.search(cleaned))


class GoodbyeProcessor(FrameProcessor):
    """P0-3 fix: end the call shortly after the AGENT says a GENUINE goodbye — but only once
    the scripted flow has actually completed, so a stray farewell-ish phrase can't hang up
    mid-conversation.

    This processor sits AFTER the LLM in the pipeline and watches the agent's own output:

      - It accumulates the streamed assistant text (LLMTextFrame) for the current turn.
      - On LLMFullResponseEndFrame (the turn is complete) it:
          * counts the completed assistant turn,
          * marks the quote as delivered once the turn contains it,
          * and only ARMS the hangup if BOTH (a) the quote has been delivered AND
            (b) at least MIN_ASSISTANT_TURNS_BEFORE_GOODBYE completed turns have happened,
            AND the cleaned turn text (quote removed) matches a genuine closing.
      - On the next BotStoppedSpeakingFrame (the farewell has finished playing out of the
        TTS) it queues an EndFrame. The Twilio serializer's auto_hang_up then drops the real
        phone call. MAX_CALL_SECS stays as a backstop.

    We match on the *completed* turn (not mid-stream), exclude the quote text from matching,
    and wait for bot-stopped-speaking so we never cut the agent off mid-farewell.
    """

    def __init__(self, quote: str, mode: str = "outbound"):
        super().__init__()
        self.task: PipelineTask | None = None  # set after the task is created
        self._quote = quote
        # mode == "inbound" means Ishaan dialed us (assistant persona, NO motivational
        # quote). The outbound gate requires the quote to have been delivered before a
        # farewell may hang up; inbound has no quote, so we drop that requirement and only
        # require a genuine goodbye after at least one real exchange.
        self._mode = mode
        self._buffer = ""          # assistant text for the in-flight turn
        self._turns = 0            # completed GENERATED assistant turns so far
        self._quote_delivered = False
        self._armed = False        # farewell detected, waiting for speech to finish
        self._ending = False       # EndFrame already queued (one-shot)

    def _quote_in(self, text: str) -> bool:
        """Has the quote (or its core sentence) appeared in this turn?"""
        if not self._quote:
            return False
        # _strip_quote shortens the text iff it found the quote/inner sentence.
        return len(_strip_quote(text, self._quote)) < len(text)

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if isinstance(frame, LLMTextFrame):
            self._buffer += frame.text
        elif isinstance(frame, LLMFullResponseEndFrame):
            text = self._buffer.strip()
            self._buffer = ""
            if text:
                self._turns += 1
                if not self._quote_delivered and self._quote_in(text):
                    self._quote_delivered = True
                    logger.info("quote delivered -> goodbye gating now active")
                if self._mode == "inbound":
                    # No quote in the assistant flow when Ishaan calls in: a genuine
                    # goodbye after at least one real generated exchange may hang up. We
                    # still require >=1 completed turn so a stray farewell-ish phrase in
                    # the model's very first reply can't drop the call instantly.
                    gate_ok = self._turns >= 1
                else:
                    gate_ok = (
                        self._quote_delivered
                        and self._turns >= MIN_ASSISTANT_TURNS_BEFORE_GOODBYE
                    )
                if not self._armed and gate_ok and detect_goodbye(text, self._quote):
                    logger.info(
                        f"genuine goodbye detected (turn {self._turns}, quote delivered) "
                        f"-> will hang up: {text!r}"
                    )
                    self._armed = True
                elif not self._armed and detect_goodbye(text, self._quote):
                    logger.info(
                        f"farewell-ish phrase ignored (gate not met: "
                        f"quote_delivered={self._quote_delivered} turns={self._turns}): {text!r}"
                    )
        elif (
            isinstance(frame, BotStoppedSpeakingFrame)
            and self._armed
            and not self._ending
            and self.task is not None
        ):
            self._ending = True
            logger.info("farewell finished speaking -> queueing EndFrame (auto hang up)")
            await self.task.queue_frame(EndFrame())

        await self.push_frame(frame, direction)


@app.on_event("startup")
async def _preload_models() -> None:
    # P1-3: pay the Smart Turn ONNX load cost ONCE at app startup (before any call), off the
    # request path, so /ws never blocks the event loop reloading the model per call.
    _get_warm_turn()


@app.get("/health")
def health() -> dict:
    return {"ok": True}


@app.api_route("/twiml", methods=["GET", "POST"])
async def twiml(request: Request) -> PlainTextResponse:
    """Twilio fetches this when the outbound call connects. We hand it back a
    <Connect><Stream> pointed at our websocket, so the call's audio is bridged to Pipecat."""
    # Twilio POSTs form-encoded data; fall back to query params so a missing
    # python-multipart (or a GET-configured webhook) can't 500 the webhook.
    try:
        form = await request.form()
        call_sid = form.get("CallSid") or request.query_params.get("CallSid") or "unknown"
        direction = form.get("Direction") or request.query_params.get("Direction") or ""
        from_number = form.get("From") or request.query_params.get("From") or ""
    except Exception:  # noqa: BLE001
        call_sid = request.query_params.get("CallSid", "unknown")
        direction = request.query_params.get("Direction", "")
        from_number = request.query_params.get("From", "")
    # INBOUND vs OUTBOUND persona: Twilio sends Direction=inbound for an incoming call
    # (Ishaan dialed the number) and Direction=outbound-api for our REST-placed 7 AM call.
    # We map that to a simple mode the pipeline understands and pass it through to /ws.
    # Default to "outbound" so the existing morning flow is unchanged if Direction is absent.
    mode = "inbound" if str(direction).lower() == "inbound" else "outbound"
    # Caller authorization (CONTRACT.md): OUTBOUND is always authorized (we dialed the owner);
    # INBOUND is authorized only if From is on the allowlist. We compute it here and pass it +
    # the caller number to /ws via <Parameter> (same trusted channel as token/mode). /ws uses
    # `authorized` to decide whether to offer tools, and `caller` to key cross-call memory.
    caller = _normalize_e164(from_number)
    authorized = is_authorized(direction, from_number)
    # P1-4: evict abandoned entries first so QUOTES/WS_TOKENS can't grow unbounded.
    _evict_stale()
    now = time.monotonic()
    # OUTBOUND pre-generates the motivational quote while Twilio sets up the call. INBOUND
    # is an assistant persona with NO quote, so we skip that NVIDIA call (less latency, no
    # wasted credits) and store an empty string; /ws's inbound path never uses it.
    QUOTES[call_sid] = ((generate_quote() if mode == "outbound" else ""), now)
    # Security: mint a per-call token, store it server-side keyed by CallSid, and embed it
    # in the ws URL. /ws rejects any connection whose token doesn't match — so a stranger
    # who finds the public wss endpoint can't open a session and burn STT/LLM/TTS credits.
    token = secrets.token_urlsafe(24)
    WS_TOKENS[call_sid] = (token, now)
    host = request.headers.get("host")
    # Per Twilio docs, <Stream url> does NOT support query-string parameters — they're
    # dropped on the wss upgrade, and a raw "&" between two params is also invalid XML
    # (the cause of the inbound "application error"). So the URL is clean, and ALL custom
    # data (per-call token + persona mode) is passed via <Parameter> children, which Twilio
    # echoes in the 'start' event's start.customParameters — the officially-supported channel
    # that /ws reads. https://www.twilio.com/docs/voice/twiml/stream#custom-parameters
    ws_url = f"wss://{host}/ws"
    logger.info(
        f"/twiml call_sid={call_sid} mode={mode} authorized={authorized} "
        f"-> stream {ws_url} (token via <Parameter>)"
    )
    # `caller` is the NORMALIZED From (digits + optional leading '+'), so it's XML-safe; we pass
    # it (not the raw From) both for memory keying and to avoid any XML-injection surface.
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        f"<Response><Connect><Stream url=\"{ws_url}\">"
        f"<Parameter name=\"token\" value=\"{token}\"/>"
        f"<Parameter name=\"mode\" value=\"{mode}\"/>"
        f"<Parameter name=\"authorized\" value=\"{'true' if authorized else 'false'}\"/>"
        f"<Parameter name=\"caller\" value=\"{caller}\"/>"
        "</Stream></Connect></Response>"
    )
    return PlainTextResponse(xml, media_type="application/xml")


@app.websocket("/ws")
async def ws(websocket: WebSocket) -> None:
    await websocket.accept()
    # P1-4: harden startup. The caller may not answer, or may hang up before Twilio sends
    # the 'start' frame; receive_text() then raises (disconnect) or returns junk. Wrap both
    # reads so a dropped/early call logs and returns cleanly instead of throwing a 500.
    try:
        await websocket.receive_text()  # 'connected'
        start = json.loads(await websocket.receive_text())  # 'start'
        stream_sid = start["start"]["streamSid"]
        call_sid = start["start"]["callSid"]
    except Exception as e:  # noqa: BLE001
        logger.warning(f"/ws closed before start handshake completed: {type(e).__name__}: {e}")
        try:
            await websocket.close()
        except Exception:  # noqa: BLE001
            pass
        return

    # Security: per-call token, DUAL-CHANNEL + fail-safe. /twiml minted a token for this
    # CallSid and delivered it BOTH on the ws URL query string AND as a <Stream><Parameter>
    # (which Twilio echoes in start.start.customParameters). We accept a match from EITHER
    # channel, so even if the query string were dropped on the wss upgrade, the real call
    # still passes (customParameters always carries it). We reject (close 1008) ONLY when a
    # token was minted for this CallSid and NEITHER channel presents a matching value — that
    # blocks a no-token scanner without risking the real 7 AM call.
    # (The offline sim mints a real token via /twiml and presents it on at least one channel,
    # so it exercises this exact auth path — no test backdoor that could weaken prod auth.)
    expected = WS_TOKENS.pop(call_sid, (None, 0.0))[0]
    if expected is not None:
        qs_token = websocket.query_params.get("token")
        try:
            cp_token = start["start"].get("customParameters", {}).get("token")
        except (AttributeError, TypeError):
            cp_token = None
        ok = any(
            t is not None and secrets.compare_digest(t, expected)
            for t in (qs_token, cp_token)
        )
        if not ok:
            logger.warning(f"/ws rejected: bad/missing token for call_sid={call_sid}")
            try:
                await websocket.close(code=1008)  # policy violation
            except Exception:  # noqa: BLE001
                pass
            return

    # Persona mode (inbound = Ishaan dialed us; outbound = the 7 AM call). Read it from the
    # SAME dual channels as the token: start.customParameters (Twilio-delivered <Parameter>)
    # first, then the ws URL query string. Default "outbound" so the morning flow is unchanged
    # if mode is absent. We sanitize to the two known values.
    try:
        cp_mode = start["start"].get("customParameters", {}).get("mode")
    except (AttributeError, TypeError):
        cp_mode = None
    mode = (cp_mode or websocket.query_params.get("mode") or "outbound").lower()
    if mode != "inbound":
        mode = "outbound"

    # Caller authorization + caller number, read from the SAME dual channels as token/mode.
    # `authorized` decides whether the agent is offered the Mac-control tools at all (an
    # unauthorized inbound caller gets the friendly NO-TOOLS persona). `caller` is the
    # normalized From, used to key cross-call memory. We FAIL CLOSED: only an explicit "true"
    # authorizes; anything else (missing, malformed) → no tools. (/twiml always sends "true"
    # for outbound, so the morning call is unaffected.)
    try:
        cp = start["start"].get("customParameters", {}) or {}
    except (AttributeError, TypeError):
        cp = {}
    authorized_raw = cp.get("authorized") or websocket.query_params.get("authorized") or ""
    authorized = str(authorized_raw).lower() == "true"
    caller = cp.get("caller") or websocket.query_params.get("caller") or ""

    # OUTBOUND uses the pre-generated motivational quote (with a fresh fallback if it was
    # somehow lost). INBOUND has no quote — the assistant persona never delivers one.
    if mode == "outbound":
        quote = (QUOTES.pop(call_sid, (None, 0.0))[0]) or generate_quote()
    else:
        QUOTES.pop(call_sid, None)  # discard the unused empty placeholder
        quote = ""
    greeting = INBOUND_GREETING if mode == "inbound" else GREETING
    logger.info(
        f"/ws connected stream_sid={stream_sid} call_sid={call_sid} "
        f"mode={mode} authorized={authorized}"
    )

    serializer = TwilioFrameSerializer(
        stream_sid=stream_sid,
        call_sid=call_sid,
        account_sid=os.environ["TWILIO_ACCOUNT_SID"],
        auth_token=os.environ["TWILIO_AUTH_TOKEN"],  # lets Pipecat hang the call up at the end
    )
    transport = FastAPIWebsocketTransport(
        websocket=websocket,
        params=FastAPIWebsocketParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
            audio_in_sample_rate=SR,
            audio_out_sample_rate=SR,
            add_wav_header=False,
            vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=VAD_STOP_SECS)),
            serializer=serializer,
        ),
    )

    stt = DeepgramSTTService(api_key=os.environ["DEEPGRAM_API_KEY"], sample_rate=SR)
    llm = OpenAILLMService(
        api_key=os.environ["NVIDIA_API_KEY"],
        base_url="https://integrate.api.nvidia.com/v1",
        model=LLM_MODEL,
        params=OpenAILLMService.InputParams(
            # P2-3: match the validated m0_local_bot.py (0.2) — the scripted morning flow
            # (react -> exact quote -> short chat -> goodbye) wants focus, not creativity.
            # Lower temp also reinforces the "don't re-greet" instruction (see dry-run).
            temperature=0.2,
            top_p=0.95,
            max_tokens=4096,
            extra={"extra_body": {"chat_template_kwargs": {"enable_thinking": False}}},
        ),
    )
    # Cap the free endpoint's tail latency (documented to stall 20-30s); SDK retries fresh.
    llm._client = llm._client.with_options(timeout=8.0, max_retries=2)
    tts = CartesiaTTSService(
        api_key=os.environ["CARTESIA_API_KEY"],
        voice_id=CARTESIA_VOICE_ID,
        sample_rate=SR,
        settings=CartesiaTTSService.Settings(
            generation_config=GenerationConfig(speed=CARTESIA_SPEED)
        ),
    )

    # --- Build the system prompt + tool surface based on AUTHORIZATION --------------------
    # AUTHORIZED: full registry tools + GLM factory + cross-call memory. The persona is the
    # morning-quote flow (outbound) or the assistant flow (inbound), both with the general
    # MAC CONTROL + protocols block. We also splice in any remembered facts about this caller.
    # UNAUTHORIZED: NO tools, the friendly no-tools persona, NO factory/registry/broker/memory.
    broker = None
    recorder = None
    task_holder = _TaskHolder()
    if authorized:
        # Cross-call memory: recall() returns "" for an unknown/first-time caller (so the prompt
        # is unchanged), or a compact "Things to remember about this caller:" block we append.
        base_prompt = inbound_system_prompt() if mode == "inbound" else system_prompt(quote)
        mem = ""
        try:
            mem = agent_memory.recall(caller)
        except Exception:  # noqa: BLE001 — memory must never break the call
            mem = ""
        prompt = (base_prompt + "\n\n" + mem) if mem else base_prompt

        # Per-call confirmation broker (CONFIRM gating) + recorder (capture this call for the
        # memory store; finalized in the `finally` below).
        broker = mac_tools.ConfirmationBroker()
        recorder = agent_memory.CallRecorder(call_sid, direction=mode, caller=caller)
        tools = authorized_tools_schema()  # full registry + confirm/cancel/request_new_tool
    else:
        # No-tools persona for a caller we don't recognize. NOT_GIVEN (not None) is how pipecat's
        # universal LLMContext expresses "no tools" — passing None raises TypeError. (CONTRACT
        # said tools=None; the live API requires NOT_GIVEN, same intent: nothing is offered.)
        prompt = no_tools_system_prompt()
        tools = NOT_GIVEN

    # BUG 1 fix: seed the context so the model's history shows it has ALREADY greeted.
    # The exact GREETING goes in as the assistant's first turn — paired with the system
    # prompt's "never greet again", the model has nothing to restart and just continues.
    #
    # TOOL-NARRATION fix: for an AUTHORIZED call we ALSO seed one proper tool-call exchange
    # right after the greeting (see _seed_tool_example). Nemotron-nano imitates its own history;
    # without this, a single prose-narration turn poisons the call and the model stops calling
    # tools entirely. The seed makes 'call a tool' the established pattern and recovers tool use
    # even after a stray narration. Unauthorized callers have no tools, so they get no seed.
    seeded_messages: list[dict] = [
        {"role": "system", "content": prompt},
        {"role": "assistant", "content": greeting},
    ]
    if authorized:
        seeded_messages.extend(_seed_tool_example())
    context = LLMContext(messages=seeded_messages, tools=tools)

    # Voice-controlled Mac harness: for an AUTHORIZED call, wire the FULL registry + the
    # confirm/cancel/request_new_tool control tools onto the LLM. The adapters dispatch in a
    # worker thread (so blocking osascript never stalls the loop), record actions to memory,
    # and gate CONFIRM actions on the per-call broker. Skipped entirely for unauthorized calls.
    if authorized:
        build_tools_and_register(llm, context, broker, recorder, task_holder)
    # Patient endpointing: a prosody model (not a silence timer) decides when the caller is
    # done, so the agent waits him out instead of cutting him off or dead-airing.
    turn_strategies = UserTurnStrategies(
        stop=[
            # P1-3: reuse the preloaded ONNX model (no blocking reload inside the call).
            TurnAnalyzerUserTurnStopStrategy(turn_analyzer=build_turn_analyzer())
        ]
    )
    # user_params wires the strategy into the user half; the user aggregator still feeds
    # finished caller transcripts into the LLM exactly as before.
    aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(user_turn_strategies=turn_strategies),
    )

    # P0-3: pass the quote so the processor can (a) detect when it's been delivered and
    # (b) exclude its text from farewell matching.
    goodbye = GoodbyeProcessor(quote, mode=mode)  # watches the agent's completed turn for a farewell
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            aggregator.user(),
            llm,
            goodbye,
            tts,
            transport.output(),
            aggregator.assistant(),
        ]
    )
    task = PipelineTask(
        pipeline,
        params=PipelineParams(allow_interruptions=True, audio_in_sample_rate=SR, audio_out_sample_rate=SR),
    )
    goodbye.task = task  # hand the processor the task so it can queue EndFrame on goodbye
    # Hand the live task to the tool adapters so request_new_tool can queue its "building it
    # now" filler frame the moment it's called (the adapters closed over this holder above).
    task_holder.task = task

    # BUG 1 fix: speak the opening as a FIXED line exactly once — no LLMRunFrame, so an
    # interruption can never trigger a regeneration that loops the intro. We hold off until
    # the caller's audio stream is live (on_client_connected) so the first word isn't lost.
    @transport.event_handler("on_client_connected")
    async def _greet(_t, _c):
        await asyncio.sleep(0.3)
        # append_to_context=False: the greeting is already in the context above, so we don't
        # want the assistant aggregator to add it a SECOND time. `greeting` is the persona's
        # fixed opener (morning GREETING for outbound, INBOUND_GREETING when Ishaan dialed in).
        await task.queue_frames([TTSSpeakFrame(greeting, append_to_context=False)])

    @transport.event_handler("on_client_disconnected")
    async def _bye(_t, _c):
        await task.cancel()

    async def _max_duration_guard():
        await asyncio.sleep(MAX_CALL_SECS)
        # P1-2: avoid a double EndFrame. If the goodbye flow already armed/queued the hangup,
        # the call is already finishing — don't pile on a second EndFrame.
        if goodbye._armed or goodbye._ending:
            logger.info("max call duration reached but goodbye already ending the call — skip")
            return
        logger.info("max call duration reached — ending call")
        await task.queue_frames([EndFrame()])

    runner = PipelineRunner(handle_sigint=False)
    guard = asyncio.create_task(_max_duration_guard())
    try:
        await runner.run(task)
    finally:
        guard.cancel()
        # MEMORY: persist + summarize this call (authorized calls only — unauthorized ones have
        # no recorder). Best-effort and time-bounded: summarization runs in a worker thread so
        # it doesn't block the loop, and we cap the wait so teardown isn't delayed more than a
        # few seconds. Any failure is swallowed — memory must never break call teardown.
        if recorder is not None:
            try:
                messages = context.get_messages() or context.messages
            except Exception:  # noqa: BLE001
                messages = None
            try:
                await asyncio.wait_for(
                    asyncio.to_thread(recorder.finalize, messages), timeout=5.0
                )
            except Exception:  # noqa: BLE001 — incl. TimeoutError: don't delay teardown
                logger.warning("memory finalize skipped (error or timeout)")
        logger.info(f"/ws call {call_sid} finished")
