"""
Milestone 1/2 — the REAL voice engine over the phone (Twilio Media Streams + Pipecat).

This is the project's own pipeline — the same brain/ears/voice as m0_local_bot.py — but
the transport is a Twilio phone call instead of your laptop mic:

    Twilio call ─► /twiml (<Connect><Stream>) ─► wss://…/ws ─┐
       caller audio (8k μ-law) ─► Deepgram STT ─► Nemotron LLM ─► Cartesia TTS ─► caller
                                  (ears)          (brain)          (OUR voice: Brooke)

Twilio does NONE of the speaking here — every spoken word is Cartesia Sonic (CARTESIA_VOICE_ID),
exactly the voice configured in .env. That's the difference from call_me.py, which used Twilio's
built-in Polly <Say>. The motivational quote is generated by Nemotron and woven into the call.

Launched behind a cloudflared tunnel by run_morning_call.py (Twilio needs a public wss URL).
"""

import asyncio
import html
import json
import os
import re
import secrets
import time
from concurrent.futures import ThreadPoolExecutor

from dotenv import load_dotenv
from fastapi import FastAPI, Request, WebSocket
from fastapi.responses import PlainTextResponse
from loguru import logger

from pipecat.audio.turn.smart_turn.base_smart_turn import SmartTurnParams
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import (
    BotStoppedSpeakingFrame,
    EndFrame,
    Frame,
    LLMFullResponseEndFrame,
    LLMTextFrame,
    TTSSpeakFrame,
)
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext, NOT_GIVEN
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.serializers.twilio import TwilioFrameSerializer
from pipecat.services.cartesia.tts import CartesiaTTSService, GenerationConfig
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.websocket.fastapi import (
    FastAPIWebsocketParams,
    FastAPIWebsocketTransport,
)
from pipecat.turns.user_stop import TurnAnalyzerUserTurnStopStrategy
from pipecat.turns.user_turn_strategies import UserTurnStrategies
from pipecat.utils.env import env_truthy

load_dotenv()

from call_me import generate_quote  # noqa: E402  (resilient Nemotron quote + fallback)
from turn_helpers import PatientSmartTurnV3  # noqa: E402  (shared patient endpointer)
from prompts import load_prompt  # noqa: E402  (system prompt lives in prompts/prompts.json)

# agent_memory gives the agent cross-call memory (CallRecorder + recall). It lives under
# src/ (cwd=src in the daemon), same as call_me/turn_helpers. The voice-controlled Mac
# harness that used to live here (a large tool registry + a GLM tool factory) has been
# removed; this is now a tools-less voice agent.
import agent_memory  # noqa: E402  (CallRecorder + recall - cross-call memory)
import cekura_observability  # noqa: E402  (best-effort post-call metrics export)

# --- The voice. THIS is "our voice" — Cartesia Sonic, same id as the local bot. --------
CARTESIA_VOICE_ID = os.getenv("CARTESIA_VOICE_ID") or "e07c00bc-4134-4eae-9ea4-1a55fb45746b"  # Brooke
CARTESIA_SPEED = float(os.getenv("CARTESIA_SPEED", "0.95"))
LLM_MODEL = os.getenv("NVIDIA_LLM_MODEL", "nvidia/nemotron-3-nano-30b-a3b")
# Hard cap so an unattended morning call can't run forever ("a couple of minutes").
# This is now a BACKSTOP only — the call normally ends itself when the agent says goodbye.
MAX_CALL_SECS = float(os.getenv("MAX_CALL_SECS", "150"))
# Telephony audio is 8 kHz μ-law; run the whole pipeline at 8k so nothing has to guess.
SR = 8000

# The opening line is spoken VERBATIM and exactly ONCE. See BUG 1 fix below: we no longer let
# the LLM *generate* the open (an LLMRunFrame re-runs on every interruption and loops the intro).
# A fixed TTSSpeakFrame can't be regenerated, so the call can only move forward.
#
# General-purpose agent: nothing is hardcoded to one person. The caller's name comes from a
# database keyed by their phone number (see caller_display_name); when we can't identify them
# we greet without a name.
def caller_display_name(phone: str) -> str | None:
    """Look up the caller's name in the contacts database by phone number, or None if unknown.

    TODO(db): wire this to the real datastore. For now it returns None so the agent stays
    general-purpose and greets name-free. Must never raise — a failed lookup just means 'unknown'."""
    return None


def greeting_for(name: str | None, mode: str) -> str:
    """The fixed spoken opener, built per call. `name` is the caller's looked-up name (None when
    unknown, in which case the greeting is name-free). Same mechanism for both directions: a fixed
    TTSSpeakFrame seeded into context as the assistant's first turn."""
    who = f" {name}" if name else " there"
    if mode == "inbound":
        return f"Hi{who}! Thanks for calling. How are you doing today?"
    return f"Hi{who}! Thanks for taking a moment to chat. How are you doing today?"


# --- CALLER AUTHORIZATION (owner-only Mac control) ----------------------------
# Tools are OFFERED to the model ONLY for an AUTHORIZED call (CONTRACT.md "Caller
# authorization"): the 7 AM OUTBOUND call (we dialed the owner) is always authorized; an
# INBOUND call is authorized IFF the caller's number is on the allowlist. An unauthorized
# caller gets a friendly NO-TOOLS persona — it can chat but cannot control this Mac.
# AUTHORIZED_CALLERS is a comma-separated E.164 list; it DEFAULTS to TARGET_PHONE_NUMBER so
# the owner's own number works out of the box. Caller ID can be spoofed, so this is
# access-control (not crypto) — the per-call ws token still blocks non-Twilio scanners.
def _normalize_e164(num: str | None) -> str:
    """Normalize a phone number to DIGITS ONLY for allowlist comparison — drop the '+', spaces,
    and punctuation so '+1 (415) 555-0100', '+14155550100', and '14155550100' all compare equal.
    Digits-only is deliberately forgiving: an owner-allowlist match must not fail just because
    Twilio sends '+E.164' while AUTHORIZED_CALLERS/TARGET_PHONE_NUMBER was written without the '+'
    (or with spacing). Used both for the allowlist check and as the cross-call memory key."""
    if not num:
        return ""
    return re.sub(r"\D", "", str(num))


def _authorized_callers() -> set[str]:
    """The normalized allowlist of numbers permitted to control the Mac on an INBOUND call.
    Read fresh each call so a .env change doesn't require a restart. Defaults to
    TARGET_PHONE_NUMBER when AUTHORIZED_CALLERS is unset."""
    raw = os.getenv("AUTHORIZED_CALLERS") or os.getenv("TARGET_PHONE_NUMBER") or ""
    return {_normalize_e164(p) for p in raw.split(",") if p.strip()}


def is_authorized(direction: str, from_number: str | None) -> bool:
    """True if this call may use tools. OUTBOUND (anything not 'inbound') is always authorized —
    we placed the call to the owner. INBOUND is authorized only if From is on the allowlist."""
    if str(direction).lower() != "inbound":
        return True
    return _normalize_e164(from_number) in _authorized_callers()

# --- ENDPOINTING on the phone -------------------------------------------------
# A short VAD pause only *triggers* the turn decision; PatientSmartTurnV3 (a prosody
# model) makes the real call, so the agent waits out mid-sentence pauses instead of
# barging in. THRESHOLD high = "don't interrupt me"; STOP_SECS = hard ceiling so we
# still respond promptly when he's genuinely done. Mirrors the local-mic bot's tuning,
# nudged a touch more conservative for telephony jitter.
VAD_STOP_SECS = float(os.getenv("VAD_STOP_SECS", "0.4"))
SMART_TURN_THRESHOLD = float(os.getenv("SMART_TURN_THRESHOLD", "0.7"))
SMART_TURN_STOP_SECS = float(os.getenv("SMART_TURN_STOP_SECS", "2.5"))

# P0-3: phrases that mark the AGENT's turn as a GENUINE closing. Matched on the
# assistant's completed message once the LLM finishes (see GoodbyeProcessor). Tightened
# toward real sign-offs: a bare "bye" plus the warm wrap-ups the prompt asks for. We
# deliberately DROP loose matches like "have a good one" mid-sentence and only arm AFTER
# the quote was delivered + >=2 completed assistant turns, so a stray farewell-ish phrase
# (e.g. "take care of yourself" said mid-chat) can't hang up early.
GOODBYE_RE = re.compile(
    r"\b(good ?bye|bye now|bye bye|talk (to you )?soon|"
    r"take care(\s*,?\s*\w+)?\s*[.!]|"
    r"have a (great|wonderful|good) (day|one)\b)",
    re.IGNORECASE,
)
# A plain trailing "bye" / "goodbye" at the very end of the turn also counts as a close.
GOODBYE_TAIL_RE = re.compile(r"(good ?bye|bye)\s*[.!]*\s*$", re.IGNORECASE)

# P0-3: minimum completed assistant turns before a farewell may arm the hangup. The
# greeting is turn 0 (seeded, not generated); the model's quote-delivery reply is turn 1;
# we require the agent to have spoken at least this many GENERATED turns so a farewell can
# only land after the scripted flow (react -> quote -> a little chat) has actually happened.
MIN_ASSISTANT_TURNS_BEFORE_GOODBYE = int(os.getenv("MIN_GOODBYE_TURNS", "2"))

app = FastAPI()
BACKGROUND_TASKS: set[asyncio.Task] = set()


def _run_in_background(func, *args, **kwargs) -> None:
    """Run teardown/callback work without extending the live call lifecycle."""
    task = asyncio.create_task(asyncio.to_thread(func, *args, **kwargs))
    BACKGROUND_TASKS.add(task)
    task.add_done_callback(BACKGROUND_TASKS.discard)

# P1-4: Quote pre-generated at /twiml time (while Twilio sets up the call), keyed by
# CallSid, so the greeting is instant and the exact quote is guaranteed into the prompt.
# Values are (quote, created_monotonic) so abandoned calls (caller never answers, so /ws
# never pops the key) can be evicted instead of leaking forever. Tokens for the per-call
# /ws auth live alongside, same lifecycle.
QUOTES: dict[str, tuple[str, float]] = {}
WS_TOKENS: dict[str, tuple[str, float]] = {}
# How long a pre-generated quote/token may sit unclaimed before we evict it, and a hard
# cap on dict size as a belt-and-suspenders against a flood of /twiml hits.
QUOTE_TTL_SECS = float(os.getenv("QUOTE_TTL_SECS", "600"))  # 10 min
QUOTE_MAX_ENTRIES = int(os.getenv("QUOTE_MAX_ENTRIES", "256"))


def _evict_stale(now: float | None = None) -> None:
    """P1-4: drop quote/token entries older than the TTL, and hard-cap dict size.

    Called on every /twiml so abandoned calls (no matching /ws) can't grow QUOTES/WS_TOKENS
    without bound. Cheap: a single pass over what is normally a tiny dict.
    """
    now = time.monotonic() if now is None else now
    for store in (QUOTES, WS_TOKENS):
        stale = [k for k, (_v, ts) in store.items() if now - ts > QUOTE_TTL_SECS]
        for k in stale:
            store.pop(k, None)
        # Hard size cap: if still oversized, evict oldest first.
        if len(store) > QUOTE_MAX_ENTRIES:
            for k, _ in sorted(store.items(), key=lambda kv: kv[1][1])[
                : len(store) - QUOTE_MAX_ENTRIES
            ]:
                store.pop(k, None)
    if stale:
        logger.info(f"evicted {len(stale)} stale quote/token entries")


# P1-3: preload the Smart Turn v3 ONNX model ONCE at import time. Constructing a
# PatientSmartTurnV3 loads a WhisperFeatureExtractor + an onnxruntime InferenceSession,
# which blocks ~0.5-1s. Doing that inside /ws stalled the event loop right after the call
# connected. We build one warm instance here (paying the cost at startup) and reuse its
# loaded session + feature extractor for every call. Each call still gets a FRESH analyzer
# object so the per-call audio buffer / silence counters / thread executor stay isolated —
# only the expensive, immutable, read-only model artifacts (_session, _feature_extractor)
# are shared. We don't edit turn_helpers.py; instead we allocate a bare instance with
# __new__ and replay the cheap base-class init by hand, then graft on the warm artifacts.
_WARM_TURN: "PatientSmartTurnV3 | None" = None


def _get_warm_turn() -> "PatientSmartTurnV3":
    global _WARM_TURN
    if _WARM_TURN is None:
        logger.info("preloading Smart Turn v3 ONNX model (one-time, at startup)…")
        _WARM_TURN = PatientSmartTurnV3(
            completion_threshold=SMART_TURN_THRESHOLD,
            params=SmartTurnParams(stop_secs=SMART_TURN_STOP_SECS),
        )
        logger.info("Smart Turn v3 model preloaded")
    return _WARM_TURN


def build_turn_analyzer() -> "PatientSmartTurnV3":
    """Return a fresh per-call PatientSmartTurnV3 that REUSES the preloaded ONNX session +
    feature extractor (no blocking model reload inside /ws). Per-call mutable state is all
    fresh, so this is safe even if calls were to overlap."""
    warm = _get_warm_turn()
    params = SmartTurnParams(stop_secs=SMART_TURN_STOP_SECS)

    a = PatientSmartTurnV3.__new__(PatientSmartTurnV3)
    # --- replay BaseTurnAnalyzer.__init__ (sample rate bookkeeping) ---
    a._init_sample_rate = None
    a._sample_rate = 0
    # --- replay BaseSmartTurn.__init__ (per-call inference state) ---
    a._params = params
    a._stop_ms = params.stop_secs * 1000
    a._audio_buffer = []
    a._speech_triggered = False
    a._silence_ms = 0
    a._speech_start_time = 0
    a._executor = ThreadPoolExecutor(max_workers=1)  # own thread; not shared with warm
    a._vad_start_secs = 0.0
    # --- replay LocalSmartTurnAnalyzerV3.__init__ tail, but SKIP the heavy load ---
    a._log_data = env_truthy("PIPECAT_SMART_TURN_LOG_DATA", default=False)
    a._feature_extractor = warm._feature_extractor  # immutable, safe to share
    a._session = warm._session  # ORT InferenceSession.run() is thread-safe / read-only
    # --- replay PatientSmartTurnV3.__init__ (our threshold knob) ---
    a._completion_threshold = SMART_TURN_THRESHOLD
    return a


def call_system_prompt() -> str:
    """The phone agent's persona is loaded LIVE from prompts/prompts.json (key
    'm0_local_mic_voice_agent'), so the prompt can be edited there without touching bot code and
    the change takes effect on the NEXT call (no daemon restart needed). We append only the
    minimal phone-call mechanics the deterministic greeting + goodbye-hangup depend on: keep
    turns short, don't re-greet (the opener is spoken and seeded separately), and say a clear
    goodbye to end the call. A broken or missing prompts.json falls back to a safe persona
    rather than dropping a live call."""
    try:
        persona = load_prompt("m0_local_mic_voice_agent").strip()
    except SystemExit as e:
        logger.warning(f"prompts.json load failed ({e}); using fallback persona")
        persona = "You are a warm, empathetic voice assistant. Keep replies brief and natural."
    return (
        persona + "\n\n"
        "You are on a live phone call and everything you say is spoken aloud, so keep every turn "
        "to 1-3 short, natural sentences with no markdown, lists, emoji, or stage directions. The "
        "call is ALREADY in progress and you have already greeted the caller, so do NOT greet "
        "again or repeat yourself; reply only to what they just said. When the conversation is "
        "finished, warmly say a clear goodbye to end the call."
    )


# The three call personas now all serve the SAME prompts.json persona (the project's pivot to a
# single voice agent). They remain as named entry points so the run path keeps working; the
# `quote` arg is accepted for signature compatibility but is no longer used.
def system_prompt(quote: str) -> str:
    return call_system_prompt()


def no_tools_system_prompt() -> str:
    return call_system_prompt()


def inbound_system_prompt() -> str:
    return call_system_prompt()


def _strip_quote(text: str, quote: str) -> str:
    """P0-3: remove the motivational quote (and its core sentence) from the agent text
    before farewell-matching, so words inside the quote can't arm the hangup. We strip the
    exact quote and also any long contiguous run of it, case-insensitively."""
    if not quote:
        return text
    out = text
    q = quote.strip()
    # Exact quote removal (most common: the model delivers it verbatim).
    idx = out.lower().find(q.lower())
    if idx != -1:
        out = out[:idx] + " " + out[idx + len(q) :]
    # Also strip the inner quoted sentence (between the first pair of double quotes in the
    # quote), since the model sometimes reflows surrounding words but keeps the core line.
    m = re.search(r'"([^"]{8,})"', q)
    if m:
        inner = m.group(1)
        i2 = out.lower().find(inner.lower())
        if i2 != -1:
            out = out[:i2] + " " + out[i2 + len(inner) :]
    return out


def detect_goodbye(text: str, quote: str) -> bool:
    """P0-3: True only for a GENUINE closing in the agent's turn, AFTER excluding the quote
    text. Pulled out as a free function so it can be unit-tested offline."""
    cleaned = _strip_quote(text, quote).strip()
    return bool(GOODBYE_RE.search(cleaned) or GOODBYE_TAIL_RE.search(cleaned))


class GoodbyeProcessor(FrameProcessor):
    """P0-3 fix: end the call shortly after the AGENT says a GENUINE goodbye — but only once
    the scripted flow has actually completed, so a stray farewell-ish phrase can't hang up
    mid-conversation.

    This processor sits AFTER the LLM in the pipeline and watches the agent's own output:

      - It accumulates the streamed assistant text (LLMTextFrame) for the current turn.
      - On LLMFullResponseEndFrame (the turn is complete) it:
          * counts the completed assistant turn,
          * marks the quote as delivered once the turn contains it,
          * and only ARMS the hangup if BOTH (a) the quote has been delivered AND
            (b) at least MIN_ASSISTANT_TURNS_BEFORE_GOODBYE completed turns have happened,
            AND the cleaned turn text (quote removed) matches a genuine closing.
      - On the next BotStoppedSpeakingFrame (the farewell has finished playing out of the
        TTS) it queues an EndFrame. The Twilio serializer's auto_hang_up then drops the real
        phone call. MAX_CALL_SECS stays as a backstop.

    We match on the *completed* turn (not mid-stream), exclude the quote text from matching,
    and wait for bot-stopped-speaking so we never cut the agent off mid-farewell.
    """

    def __init__(self, quote: str, mode: str = "outbound"):
        super().__init__()
        self.task: PipelineTask | None = None  # set after the task is created
        self._quote = quote
        # mode == "inbound" means Ishaan dialed us (assistant persona, NO motivational
        # quote). The outbound gate requires the quote to have been delivered before a
        # farewell may hang up; inbound has no quote, so we drop that requirement and only
        # require a genuine goodbye after at least one real exchange.
        self._mode = mode
        self._buffer = ""          # assistant text for the in-flight turn
        self._turns = 0            # completed GENERATED assistant turns so far
        self._quote_delivered = False
        self._armed = False        # farewell detected, waiting for speech to finish
        self._ending = False       # EndFrame already queued (one-shot)

    def _quote_in(self, text: str) -> bool:
        """Has the quote (or its core sentence) appeared in this turn?"""
        if not self._quote:
            return False
        # _strip_quote shortens the text iff it found the quote/inner sentence.
        return len(_strip_quote(text, self._quote)) < len(text)

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if isinstance(frame, LLMTextFrame):
            self._buffer += frame.text
        elif isinstance(frame, LLMFullResponseEndFrame):
            text = self._buffer.strip()
            self._buffer = ""
            if text:
                self._turns += 1
                if not self._quote_delivered and self._quote_in(text):
                    self._quote_delivered = True
                    logger.info("quote delivered -> goodbye gating now active")
                if self._mode == "inbound":
                    # No quote in the assistant flow when Ishaan calls in: a genuine
                    # goodbye after at least one real generated exchange may hang up. We
                    # still require >=1 completed turn so a stray farewell-ish phrase in
                    # the model's very first reply can't drop the call instantly.
                    gate_ok = self._turns >= 1
                else:
                    gate_ok = (
                        self._quote_delivered
                        and self._turns >= MIN_ASSISTANT_TURNS_BEFORE_GOODBYE
                    )
                if not self._armed and gate_ok and detect_goodbye(text, self._quote):
                    logger.info(
                        f"genuine goodbye detected (turn {self._turns}, quote delivered) "
                        f"-> will hang up: {text!r}"
                    )
                    self._armed = True
                elif not self._armed and detect_goodbye(text, self._quote):
                    logger.info(
                        f"farewell-ish phrase ignored (gate not met: "
                        f"quote_delivered={self._quote_delivered} turns={self._turns}): {text!r}"
                    )
        elif (
            isinstance(frame, BotStoppedSpeakingFrame)
            and self._armed
            and not self._ending
            and self.task is not None
        ):
            self._ending = True
            logger.info("farewell finished speaking -> queueing EndFrame (auto hang up)")
            await self.task.queue_frame(EndFrame())

        await self.push_frame(frame, direction)


@app.on_event("startup")
async def _preload_models() -> None:
    # P1-3: pay the Smart Turn ONNX load cost ONCE at app startup (before any call), off the
    # request path, so /ws never blocks the event loop reloading the model per call.
    _get_warm_turn()


@app.get("/health")
def health() -> dict:
    return {"ok": True}


@app.api_route("/twiml", methods=["GET", "POST"])
async def twiml(request: Request) -> PlainTextResponse:
    """Twilio fetches this when the outbound call connects. We hand it back a
    <Connect><Stream> pointed at our websocket, so the call's audio is bridged to Pipecat."""
    # Twilio POSTs form-encoded data; fall back to query params so a missing
    # python-multipart (or a GET-configured webhook) can't 500 the webhook.
    try:
        form = await request.form()
        call_sid = form.get("CallSid") or request.query_params.get("CallSid") or "unknown"
        direction = form.get("Direction") or request.query_params.get("Direction") or ""
        from_number = form.get("From") or request.query_params.get("From") or ""
    except Exception:  # noqa: BLE001
        call_sid = request.query_params.get("CallSid", "unknown")
        direction = request.query_params.get("Direction", "")
        from_number = request.query_params.get("From", "")
    # INBOUND vs OUTBOUND persona: Twilio sends Direction=inbound for an incoming call
    # (Ishaan dialed the number) and Direction=outbound-api for our REST-placed 7 AM call.
    # We map that to a simple mode the pipeline understands and pass it through to /ws.
    # Default to "outbound" so the existing morning flow is unchanged if Direction is absent.
    mode = "inbound" if str(direction).lower() == "inbound" else "outbound"
    # Caller authorization (CONTRACT.md): OUTBOUND is always authorized (we dialed the owner);
    # INBOUND is authorized only if From is on the allowlist. We compute it here and pass it +
    # the caller number to /ws via <Parameter> (same trusted channel as token/mode). /ws uses
    # `authorized` to decide whether to offer tools, and `caller` to key cross-call memory.
    caller = _normalize_e164(from_number)
    authorized = is_authorized(direction, from_number)
    # P1-4: evict abandoned entries first so QUOTES/WS_TOKENS can't grow unbounded.
    _evict_stale()
    now = time.monotonic()
    # OUTBOUND pre-generates the motivational quote while Twilio sets up the call. INBOUND
    # is an assistant persona with NO quote, so we skip that NVIDIA call (less latency, no
    # wasted credits) and store an empty string; /ws's inbound path never uses it.
    QUOTES[call_sid] = ((generate_quote() if mode == "outbound" else ""), now)
    # Security: mint a per-call token, store it server-side keyed by CallSid, and embed it
    # in the ws URL. /ws rejects any connection whose token doesn't match — so a stranger
    # who finds the public wss endpoint can't open a session and burn STT/LLM/TTS credits.
    token = secrets.token_urlsafe(24)
    WS_TOKENS[call_sid] = (token, now)
    host = request.headers.get("host")
    # Per Twilio docs, <Stream url> does NOT support query-string parameters — they're
    # dropped on the wss upgrade, and a raw "&" between two params is also invalid XML
    # (the cause of the inbound "application error"). So the URL is clean, and ALL custom
    # data (per-call token + persona mode) is passed via <Parameter> children, which Twilio
    # echoes in the 'start' event's start.customParameters — the officially-supported channel
    # that /ws reads. https://www.twilio.com/docs/voice/twiml/stream#custom-parameters
    ws_url = f"wss://{host}/ws"
    logger.info(
        f"/twiml call_sid={call_sid} mode={mode} authorized={authorized} "
        f"-> stream {ws_url} (token via <Parameter>)"
    )
    # `caller` is the NORMALIZED From (digits + optional leading '+'), so it's XML-safe; we pass
    # it (not the raw From) both for memory keying and to avoid any XML-injection surface.
    recording = ""
    if cekura_observability.record_calls():
        callback = html.escape(f"https://{host}/recording-status", quote=True)
        recording = (
            "<Start><Recording channels=\"dual\" track=\"both\" "
            f"recordingStatusCallback=\"{callback}\" "
            "recordingStatusCallbackEvent=\"completed\"/></Start>"
        )
    xml = (
        '<?xml version="1.0" encoding="UTF-8"?>'
        f"<Response>{recording}<Connect><Stream url=\"{ws_url}\">"
        f"<Parameter name=\"token\" value=\"{token}\"/>"
        f"<Parameter name=\"mode\" value=\"{mode}\"/>"
        f"<Parameter name=\"authorized\" value=\"{'true' if authorized else 'false'}\"/>"
        f"<Parameter name=\"caller\" value=\"{caller}\"/>"
        "</Stream></Connect></Response>"
    )
    return PlainTextResponse(xml, media_type="application/xml")


@app.api_route("/recording-status", methods=["GET", "POST"])
async def recording_status(request: Request) -> PlainTextResponse:
    """Receive Twilio's completed-recording callback and hand audio to Cekura."""
    try:
        form = await request.form()
        status = form.get("RecordingStatus") or request.query_params.get("RecordingStatus") or ""
        call_sid = form.get("CallSid") or request.query_params.get("CallSid") or ""
        recording_url = form.get("RecordingUrl") or request.query_params.get("RecordingUrl") or ""
    except Exception:  # noqa: BLE001 - Twilio callbacks should always receive a 200
        status = request.query_params.get("RecordingStatus", "")
        call_sid = request.query_params.get("CallSid", "")
        recording_url = request.query_params.get("RecordingUrl", "")
    if status == "completed" and call_sid and recording_url:
        _run_in_background(cekura_observability.recording_completed, call_sid, recording_url)
    return PlainTextResponse("ok")


@app.websocket("/ws")
async def ws(websocket: WebSocket) -> None:
    await websocket.accept()
    # P1-4: harden startup. The caller may not answer, or may hang up before Twilio sends
    # the 'start' frame; receive_text() then raises (disconnect) or returns junk. Wrap both
    # reads so a dropped/early call logs and returns cleanly instead of throwing a 500.
    try:
        await websocket.receive_text()  # 'connected'
        start = json.loads(await websocket.receive_text())  # 'start'
        stream_sid = start["start"]["streamSid"]
        call_sid = start["start"]["callSid"]
    except Exception as e:  # noqa: BLE001
        logger.warning(f"/ws closed before start handshake completed: {type(e).__name__}: {e}")
        try:
            await websocket.close()
        except Exception:  # noqa: BLE001
            pass
        return

    # Security: per-call token, DUAL-CHANNEL + fail-safe. /twiml minted a token for this
    # CallSid and delivered it BOTH on the ws URL query string AND as a <Stream><Parameter>
    # (which Twilio echoes in start.start.customParameters). We accept a match from EITHER
    # channel, so even if the query string were dropped on the wss upgrade, the real call
    # still passes (customParameters always carries it). We reject (close 1008) ONLY when a
    # token was minted for this CallSid and NEITHER channel presents a matching value — that
    # blocks a no-token scanner without risking the real 7 AM call.
    # (The offline sim mints a real token via /twiml and presents it on at least one channel,
    # so it exercises this exact auth path — no test backdoor that could weaken prod auth.)
    expected = WS_TOKENS.pop(call_sid, (None, 0.0))[0]
    if expected is not None:
        qs_token = websocket.query_params.get("token")
        try:
            cp_token = start["start"].get("customParameters", {}).get("token")
        except (AttributeError, TypeError):
            cp_token = None
        ok = any(
            t is not None and secrets.compare_digest(t, expected)
            for t in (qs_token, cp_token)
        )
        if not ok:
            logger.warning(f"/ws rejected: bad/missing token for call_sid={call_sid}")
            try:
                await websocket.close(code=1008)  # policy violation
            except Exception:  # noqa: BLE001
                pass
            return

    # Persona mode (inbound = Ishaan dialed us; outbound = the 7 AM call). Read it from the
    # SAME dual channels as the token: start.customParameters (Twilio-delivered <Parameter>)
    # first, then the ws URL query string. Default "outbound" so the morning flow is unchanged
    # if mode is absent. We sanitize to the two known values.
    try:
        cp_mode = start["start"].get("customParameters", {}).get("mode")
    except (AttributeError, TypeError):
        cp_mode = None
    mode = (cp_mode or websocket.query_params.get("mode") or "outbound").lower()
    if mode != "inbound":
        mode = "outbound"

    # Caller authorization + caller number, read from the SAME dual channels as token/mode.
    # `authorized` decides whether the agent is offered the Mac-control tools at all (an
    # unauthorized inbound caller gets the friendly NO-TOOLS persona). `caller` is the
    # normalized From, used to key cross-call memory. We FAIL CLOSED: only an explicit "true"
    # authorizes; anything else (missing, malformed) → no tools. (/twiml always sends "true"
    # for outbound, so the morning call is unaffected.)
    try:
        cp = start["start"].get("customParameters", {}) or {}
    except (AttributeError, TypeError):
        cp = {}
    authorized_raw = cp.get("authorized") or websocket.query_params.get("authorized") or ""
    authorized = str(authorized_raw).lower() == "true"
    caller = cp.get("caller") or websocket.query_params.get("caller") or ""

    # OUTBOUND uses the pre-generated motivational quote (with a fresh fallback if it was
    # somehow lost). INBOUND has no quote — the assistant persona never delivers one.
    if mode == "outbound":
        quote = (QUOTES.pop(call_sid, (None, 0.0))[0]) or generate_quote()
    else:
        QUOTES.pop(call_sid, None)  # discard the unused empty placeholder
        quote = ""
    greeting = greeting_for(caller_display_name(caller), mode)
    logger.info(
        f"/ws connected stream_sid={stream_sid} call_sid={call_sid} "
        f"mode={mode} authorized={authorized}"
    )

    serializer = TwilioFrameSerializer(
        stream_sid=stream_sid,
        call_sid=call_sid,
        account_sid=os.environ["TWILIO_ACCOUNT_SID"],
        auth_token=os.environ["TWILIO_AUTH_TOKEN"],  # lets Pipecat hang the call up at the end
    )
    transport = FastAPIWebsocketTransport(
        websocket=websocket,
        params=FastAPIWebsocketParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
            audio_in_sample_rate=SR,
            audio_out_sample_rate=SR,
            add_wav_header=False,
            vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=VAD_STOP_SECS)),
            serializer=serializer,
        ),
    )

    stt = DeepgramSTTService(api_key=os.environ["DEEPGRAM_API_KEY"], sample_rate=SR)
    llm = OpenAILLMService(
        api_key=os.environ["NVIDIA_API_KEY"],
        base_url="https://integrate.api.nvidia.com/v1",
        model=LLM_MODEL,
        params=OpenAILLMService.InputParams(
            # P2-3: match the validated m0_local_bot.py (0.2) — the scripted morning flow
            # (react -> exact quote -> short chat -> goodbye) wants focus, not creativity.
            # Lower temp also reinforces the "don't re-greet" instruction (see dry-run).
            temperature=0.2,
            top_p=0.95,
            max_tokens=4096,
            extra={"extra_body": {"chat_template_kwargs": {"enable_thinking": False}}},
        ),
    )
    # Cap the free endpoint's tail latency (documented to stall 20-30s); SDK retries fresh.
    llm._client = llm._client.with_options(timeout=8.0, max_retries=2)
    tts = CartesiaTTSService(
        api_key=os.environ["CARTESIA_API_KEY"],
        voice_id=CARTESIA_VOICE_ID,
        sample_rate=SR,
        settings=CartesiaTTSService.Settings(
            generation_config=GenerationConfig(speed=CARTESIA_SPEED)
        ),
    )

    # --- Build the system prompt based on AUTHORIZATION ----------------------------------
    # AUTHORIZED: the morning-quote persona (outbound) or the assistant persona (inbound),
    # plus cross-call memory (we splice in any remembered facts about this caller). No tools.
    # UNAUTHORIZED: the friendly no-tools persona, no memory. Neither path offers any tools
    # (the voice-controlled Mac harness was removed).
    recorder = None
    if authorized:
        # Cross-call memory: recall() returns "" for an unknown/first-time caller (so the prompt
        # is unchanged), or a compact "Things to remember about this caller:" block we append.
        base_prompt = inbound_system_prompt() if mode == "inbound" else system_prompt(quote)
        mem = ""
        try:
            mem = agent_memory.recall(caller)
        except Exception:  # noqa: BLE001 — memory must never break the call
            mem = ""
        prompt = (base_prompt + "\n\n" + mem) if mem else base_prompt

        # Recorder captures this call for the memory store (finalized in the `finally` below).
        recorder = agent_memory.CallRecorder(call_sid, direction=mode, caller=caller)
        tools = NOT_GIVEN  # tools-less voice agent: no Mac harness, nothing to offer
    else:
        # No-tools persona for a caller we don't recognize. NOT_GIVEN (not None) is how pipecat's
        # universal LLMContext expresses "no tools" — passing None raises TypeError. (CONTRACT
        # said tools=None; the live API requires NOT_GIVEN, same intent: nothing is offered.)
        prompt = no_tools_system_prompt()
        tools = NOT_GIVEN

    # BUG 1 fix: seed the context so the model's history shows it has ALREADY greeted.
    # The exact GREETING goes in as the assistant's first turn — paired with the system
    # prompt's "never greet again", the model has nothing to restart and just continues.
    seeded_messages: list[dict] = [
        {"role": "system", "content": prompt},
        {"role": "assistant", "content": greeting},
    ]
    context = LLMContext(messages=seeded_messages, tools=tools)

    # Patient endpointing: a prosody model (not a silence timer) decides when the caller is
    # done, so the agent waits him out instead of cutting him off or dead-airing.
    turn_strategies = UserTurnStrategies(
        stop=[
            # P1-3: reuse the preloaded ONNX model (no blocking reload inside the call).
            TurnAnalyzerUserTurnStopStrategy(turn_analyzer=build_turn_analyzer())
        ]
    )
    # user_params wires the strategy into the user half; the user aggregator still feeds
    # finished caller transcripts into the LLM exactly as before.
    aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(user_turn_strategies=turn_strategies),
    )

    # P0-3: pass the quote so the processor can (a) detect when it's been delivered and
    # (b) exclude its text from farewell matching.
    goodbye = GoodbyeProcessor(quote, mode=mode)  # watches the agent's completed turn for a farewell
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            aggregator.user(),
            llm,
            goodbye,
            tts,
            transport.output(),
            aggregator.assistant(),
        ]
    )
    task = PipelineTask(
        pipeline,
        params=PipelineParams(allow_interruptions=True, audio_in_sample_rate=SR, audio_out_sample_rate=SR),
    )
    goodbye.task = task  # hand the processor the task so it can queue EndFrame on goodbye

    # BUG 1 fix: speak the opening as a FIXED line exactly once — no LLMRunFrame, so an
    # interruption can never trigger a regeneration that loops the intro. We hold off until
    # the caller's audio stream is live (on_client_connected) so the first word isn't lost.
    @transport.event_handler("on_client_connected")
    async def _greet(_t, _c):
        await asyncio.sleep(0.3)
        # append_to_context=False: the greeting is already in the context above, so we don't
        # want the assistant aggregator to add it a SECOND time. `greeting` is the persona's
        # fixed opener (morning GREETING for outbound, INBOUND_GREETING when Ishaan dialed in).
        await task.queue_frames([TTSSpeakFrame(greeting, append_to_context=False)])

    @transport.event_handler("on_client_disconnected")
    async def _bye(_t, _c):
        await task.cancel()

    async def _max_duration_guard():
        await asyncio.sleep(MAX_CALL_SECS)
        # P1-2: avoid a double EndFrame. If the goodbye flow already armed/queued the hangup,
        # the call is already finishing — don't pile on a second EndFrame.
        if goodbye._armed or goodbye._ending:
            logger.info("max call duration reached but goodbye already ending the call — skip")
            return
        logger.info("max call duration reached — ending call")
        await task.queue_frames([EndFrame()])

    runner = PipelineRunner(handle_sigint=False)
    guard = asyncio.create_task(_max_duration_guard())
    try:
        await runner.run(task)
    finally:
        guard.cancel()
        try:
            messages = context.get_messages() or context.messages
        except Exception:  # noqa: BLE001
            messages = None
        # MEMORY: persist + summarize this call (authorized calls only — unauthorized ones have
        # no recorder). Best-effort and time-bounded: summarization runs in a worker thread so
        # it doesn't block the loop, and we cap the wait so teardown isn't delayed more than a
        # few seconds. Any failure is swallowed — memory must never break call teardown.
        if recorder is not None:
            try:
                await asyncio.wait_for(
                    asyncio.to_thread(recorder.finalize, messages), timeout=5.0
                )
            except Exception:  # noqa: BLE001 — incl. TimeoutError: don't delay teardown
                logger.warning("memory finalize skipped (error or timeout)")
        # Metrics export is separate from memory: include all calls, but scrub text and do
        # network I/O in the background so observability can never delay teardown.
        _run_in_background(
            cekura_observability.export_transcript,
            call_sid,
            messages,
            caller=caller,
            mode=mode,
            authorized=authorized,
        )
        logger.info(f"/ws call {call_sid} finished")
